repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace  # trims trailing whitespace
      - id: end-of-file-fixer  # ensures that a file is either empty, or ends with one newline
      - id: check-yaml  # checks yaml files for parseable syntax
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ --check ]  # ensures that all imports are sorted
