LOG_PATH: &LOG_PATH logs/app.log
UPLOAD_FOLDER: "./user_files"
ALLOWED_EXTENSIONS: {'zip'}

LOGGING:
  LEVEL: INFO

  FILE:
    LEVEL: &FILE_LEVEL INFO
    HANDLER:
      maxBytes: 1024 # 1MB = 1024 Bytes
      backupCount: 10 # max backup files
      filename: *LOG_PATH
    FORMATTER:
      #format
      fmt: "%(asctime)s - %(levelname)s - %(message)s"

  BUFFER:
    SHOWN_DEFAULT: 50  # count of last log messages stored in buffer
    LEVEL: *FILE_LEVEL
    FORMATTER:
      #format
      fmt: "%(asctime)s - %(levelname)s - %(message)s"

  WS:
    LEVEL: NOTSET
    SHOWED_COUNT: 50  # count of last log messages seen when page is opened
    EVENT_NAME: new_log  # event name for adding a new log line at frontend
    NAMESPACE: logs  # namespace name for socketio handler
    FORMATTER:
      #format
      fmt: "%(asctime)s - %(levelname)s - %(message)s"

PERIODIC_TASKS:

  DELETE_UNAVAILABLE_URLS:
    MAX_RETRIES: 2
    RUN_SCHEDULE_HOUR: "*/12"

  GET_RESPONSES_FROM_URLS:
    RUN_SCHEDULE_HOUR: "*/12"

LOG_LINES_NUMBER: 20
