"""update processing request model

Revision ID: 02cbdcf38d93
Revises: 30871ecb0662
Create Date: 2023-07-13 02:08:46.728471

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '02cbdcf38d93'
down_revision = '30871ecb0662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_processing_request', schema=None) as batch_op:

        StatusOption = sa.Enum('INPROCESS', 'SUCCEEDED', 'FAILED', 'PENDING', name='statusoption')
        StatusOption.create(op.get_bind())

        batch_op.add_column(sa.Column(
            'status',
            StatusOption,
            nullable=False,
            server_default='PENDING',
        ))
        batch_op.add_column(sa.Column('task_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('errors_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_urls', sa.ARRAY(sa.String()), nullable=True))
        batch_op.create_index(batch_op.f('ix_file_processing_request_task_id'), ['task_id'], unique=False)
        batch_op.drop_column('errors')
        batch_op.drop_column('processed_urls')
        batch_op.drop_column('is_finished')
        batch_op.drop_column('total_urls')


def downgrade():
    with op.batch_alter_table('file_processing_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_urls', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_finished', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processed_urls', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('errors', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_file_processing_request_task_id'))
        batch_op.drop_column('error_urls')
        batch_op.drop_column('errors_count')
        batch_op.drop_column('processed_count')
        batch_op.drop_column('total_count')
        batch_op.drop_column('task_id')
        batch_op.drop_column('status')

        request_status = sa.Enum('INPROCESS', 'SUCCEEDED', 'FAILED', 'PENDING', name='statusoption')
        request_status.drop(op.get_bind())
