"""Initial migration.

Revision ID: 30871ecb0662
Revises: 
Create Date: 2023-07-02 03:40:04.855314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30871ecb0662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_processing_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_urls', sa.Integer(), nullable=True),
    sa.Column('processed_urls', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('full_url', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('domain_zone', sa.String(), nullable=False),
    sa.Column('url_path', sa.String(), nullable=True),
    sa.Column('query_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('unavailable_count', sa.Integer(), nullable=True),
    sa.Column('screenshot', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_resource_domain_zone'), ['domain_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_resource_full_url'), ['full_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_web_resource_uuid'), ['uuid'], unique=False)

    op.create_table('news_feed_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('STATUS_CHANGED', 'RESOURCE_ADDED', 'RESOURCE_DELETED', name='eventtype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['web_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_resource_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['web_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_resource_status')
    op.drop_table('news_feed_item')
    with op.batch_alter_table('web_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_resource_uuid'))
        batch_op.drop_index(batch_op.f('ix_web_resource_full_url'))
        batch_op.drop_index(batch_op.f('ix_web_resource_domain_zone'))

    op.drop_table('web_resource')
    op.drop_table('file_processing_request')
    # ### end Alembic commands ###
